### ISSUE TITLE
Built-in search page doesn't show results on page load

### ISSUE THREAD

**Issue by Regaez** [trilbymedia/grav-plugin-tntsearch#10]
The plugin template for the in-built search page doesn't show pre-queried results, e.g. when navigating to `/search?q=findthis`. By default, it only shows results after an AJAX request.

The `query` and `tntsearch_results` are already available on the search page as twig variables, they just need to be rendered. I think this could be fixed by simply adjusting the default templates.

**Comment by w00fz** [comment]
This actually introduced an issue (results show also for dropdowns which is not intented behavior).
I am going to reopen for the time being, although I already have a proper fix for it.
