### ISSUE TITLE
Warning: Please use `require("history").createBrowserHistory` instead of `require("history/createBrowserHistory")`.

### ISSUE THREAD

**Issue by LeMoussel** [trilbymedia/grav-plugin-tntsearch#101]
Hi,

in the FireFox browser console, I have this Warning message
`Warning: Please use `require("history").createBrowserHistory` instead of `require("history/createBrowserHistory")`. Support for the latter will be removed in the next major release.`

![image](https://user-images.githubusercontent.com/1816573/91629946-9bd1b200-e9cd-11ea-9641-a8a28d5781d2.png)

**Comment by w00fz** [comment]
This was fixed.
