### ISSUE TITLE
Query parameter "q" does not work

### ISSUE THREAD

**Issue by janousek** [trilbymedia/grav-plugin-tntsearch#107]
Expression on this line:
https://github.com/trilbymedia/grav-plugin-tntsearch/blob/88970972ee4895102a5e3a5fa79b09f25aa3893e/tntsearch.php#L212
Returns empty string even if there is "?q=something" in the request URL.

I belive that this line should looks like this:
````
$this->query = (string)($uri->param('q', null) ?: $uri->query('q') ?: ''); 
````

Because "$uri->param('q', null)" can return "false".

**Comment by bricebou** [comment]
Thanks a lot !

**Comment by schnumsel** [comment]
Anybody created a Pull Request allready? If not I could do so...

**Comment by schnumsel** [comment]
Just did it :)

**Comment by Sthaagg** [comment]
Thank you so much ! Works like a charm !

**Comment by rhukster** [comment]
PR merged and released
