### ISSUE TITLE
Bump to vendor's v2.9 at least to get the french stemmer and more

### ISSUE THREAD

**Issue by gamahachaa** [trilbymedia/grav-plugin-tntsearch#129]
Vendor's lib is 2 years old.
Adding the French stemmer would help.

Cheers

**Comment by ViliusS** [comment]
@rhukster could you update bundled TNTSearch library and release new plugin version? There is a fair amount of fixes and new stemmers available.

**Comment by rhukster** [comment]
will do thanks.

**Comment by rhukster** [comment]
Released as 3.4.0
