### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Undefined class constant 

### ISSUE THREAD

**Issue by gour** [trilbymedia/grav-plugin-tntsearch#13]
Hello,

I'm just starting with Grav trying to make this plugin to work but get the following:

```
$ bin/plugin tntsearch index

Re-indexing Search

PHP Fatal error:  Uncaught Error: Undefined class constant 'PDO::MYSQL_ATTR_USE_BUFFERED_QUERY' in /home/gour/public_html/org/user/plugins/tntsearch/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php:184
Stack trace:
#0 /home/gour/public_html/org/user/plugins/tntsearch/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php(155): TeamTNT\TNTSearch\Indexer\TNTIndexer->createConnector(Array)
#1 /home/gour/public_html/org/user/plugins/tntsearch/vendor/teamtnt/tntsearch/src/TNTSearch.php(58): TeamTNT\TNTSearch\Indexer\TNTIndexer->createIndex('grav.index')
#2 /home/gour/public_html/org/user/plugins/tntsearch/classes/GravTNTSearch.php(108): TeamTNT\TNTSearch\TNTSearch->createIndex('grav.index')
#3 /home/gour/public_html/org/user/plugins/tntsearch/cli/IndexerCommand.php(69): Grav\Plugin\TNTSearch\GravTNTSearch->createIndex()
#4 /home/gour/public_html/org/user/plugins/tntsearch/cli/IndexerCommand.php(54): Grav\Plugin\Console\IndexerCommand->doIndex()
#5 /home/gour/public_html/org/system/src/Grav/Console/ConsoleCommand.php(29): Grav\Plugi in /home/gour/public_html/org/user/plugins/tntsearch/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php on line 184
```

Let me say that I have the following extension:

```
PDO Driver for SQLite 3.x | enabled
SQLite Library | 3.20.1
```

Any hint?

**Comment by rhukster** [comment]
You clearly don't have PDO fully installed.  That constant is part of the core PDO library.  Just having a driver is not enough.  You need `php_pdo` also.

**Comment by gour** [comment]
> You clearly don't have PDO fully installed. That constant is part of the core PDO library. Just having a driver is not enough. You need php_pdo also.

Well, `pdo_sqlite.so` and `pdo.so` are part of the same `php-pdo` package on Fedora Linux and both were installed when  got the error.

Here is also output from `phpinfo();`:

![pdo](https://user-images.githubusercontent.com/114592/33345747-a7af8802-d48d-11e7-80c6-3bb6f302d396.png)

Is the above shot OK?

**Comment by rhukster** [comment]
That looks ok, but I think the problem is that the TNTSearch library is looking for the Mysql constant even though we don't use it. You probably will need to install `pdo_myqsl.so`

**Comment by gour** [comment]
> That looks ok, but I think the problem is that the TNTSearch library is looking for the Mysql constant even though we don't use it. You probably will need to install pdo_myqsl.so

Installing `pdo_mysql.so` does help, but then Requirements have to be updated to mention it.
