### ISSUE TITLE
Search from Overrides menu field

### ISSUE THREAD

**Issue by asinyayev** [trilbymedia/grav-plugin-tntsearch#14]
I have landing page with modulars.
Сan I add a search on the menu field, if I have a different title and menu ?
http://prntscr.com/hiyhow

I need the search to work on the menu, content and title for all modular pages...

**Comment by rhukster** [comment]
You can use custom rendering templates to render the contents of modular pages into a single page.

https://github.com/trilbymedia/grav-plugin-tntsearch#providing-custom-render-templates
