### ISSUE TITLE
jQuery... why?

### ISSUE THREAD

**Issue by jimblue** [trilbymedia/grav-plugin-tntsearch#2]
Hello,

First thank you for this nice plugin 👍 !

But adding jQuery to my projects only for this plugin make me really sad...
So I was wondering if it's possible to make it dependency free?

jQuery is not necessary to make the job and with modern JS syntax I'm sure I should be an easy job.

Don't you think?

**Comment by w00fz** [comment]
Yeah totally agreed. The reason we have jQuery required right now was to get the plugin out and utilized so that we could focus on major issues, if any.

The idea, though, is that we would then revisit and add an option to decide whether to use jQuery or VanillaJS. There isn't much going on aside from Ajax calls but JS is still required so you won't be able to have no JS at all if that makes sense?

**Comment by jimblue** [comment]
Hi @w00fz ! Thanks for super fast answer!

That's a great news you plan to free us from jQuery, this is definitively the way to go. If I'm able to convert your code to vanilla JS, I'll post it here. 😄

**Comment by w00fz** [comment]
Nice! You could do a PR if you like, that would be very welcome!

**Comment by jimblue** [comment]
What is a PR?

**Comment by w00fz** [comment]
Pull Request: https://github.com/trilbymedia/grav-plugin-tntsearch/pulls

**Comment by jimblue** [comment]
Ok thanks 😄 ! I'm gonna try to make the conversion to vanilla, if it's a success I will make a PR.

**Comment by rhukster** [comment]
I'm a JS weenie and really just get by with jQuery :) Help with JS is always appreciated.

**Comment by apotropaic** [comment]
Hey guys, I used this plugin on a project of mine and wrote plain js for searching. I had already one this work in es6 javascript, so I just converted it to a more compatible version for the pull request.

**Comment by w00fz** [comment]
Nice job @apotropaic ! I'd actually prefer the es6 version with webpack/babel for es5! Who needs to read es5 anymore, right?

Thanks for the contribution, much appreciated!

**Comment by apotropaic** [comment]
I included my es6 class/module in the pull request as well `tntsearch.es6.js` Not sure what the way to make that standalone though. Any thoughts on that? Maybe just run it through online babel converter?

**Comment by w00fz** [comment]
Oh oops! I missed that.
Yeah i'll wrap up a webpack conf and let it transpile to es5. I usually keep es6 as source code and then watch/auto-transpile as i develop.
I just don't like writing es5 anymore, so i let webpack do the work for me :)

**Comment by rhukster** [comment]
JS is no longer JQuery based.
