### ISSUE TITLE
option to set search root

### ISSUE THREAD

**Issue by cord** [trilbymedia/grav-plugin-tntsearch#22]
am missing an option to limit the search to a subtree of the content tree by environment configuration (am running a multisite setup).

This could be either a configurable search index or a limitation of the search feature.

**Comment by rhukster** [comment]
You should be able to use a collection to grab any child and its descendants.  Alternatively you could provide mutliple items and set a root + taxonomy:

```
filter:
  items:
    - root@.descendants
```
