### ISSUE TITLE
multilanguage support

### ISSUE THREAD

**Issue by cord** [trilbymedia/grav-plugin-tntsearch#23]
Limit search by current language

**Comment by redrohX** [comment]
For me this is the biggest obstacle to use the plugin, since the query also returns content for other languages (with the wrong URL). I would expect search results only for the same language. So yes, would be really nice to have this. 👍

**Comment by leotiger** [comment]
From what I see, the plugin does only index content in the default language but returns the correct route based on the active language in the search results. People may believe that search results in other languages are based on truly indexed content in the language but that's not the case, as I deduce from my tests. To add the content in all available languages it's possible to use the onTNTSearchIndex event:

```
public function onTNTSearchIndex(Event $e)
{
    $fields = $e['fields'];
    $page = $e['page'];
        
    $template = $page->template();

    if (count($page->translatedLanguages())) {                
        foreach($page->translatedLanguages() as $lang => $translation) {
            $langPath = $page->path() . '/' . $template . '.' . $lang . '.md';
            if (file_exists($langPath)) {
                $translated_page = new Page();
                $translated_page->init(new \SplFileInfo($langPath));

                if ($translated_page instanceof Page) {
                    $langcontent = $lang . "content";
                    $fields->$langcontent = $translated_page->content();

                }
            }
        }
    }
}
```

This way you can index a route with all available and published language variations. Naturally you can search now for Spanish, English or whatsoever with independence of the active language but you can assume that a Spanish speaking visitor will search using terms in Spanish, etc. and if everything's configured correctly the link of the search results will point to the correct language version.

**Comment by rhukster** [comment]
Forgot we had an issue about this.  I've just added multilang support and the issue to discuss is here: https://github.com/trilbymedia/grav-plugin-tntsearch/issues/58
