### ISSUE TITLE
Compat PHP 7.2

### ISSUE THREAD

**Issue by dgaussin** [trilbymedia/grav-plugin-tntsearch#24]
Plugin is broken in PHP 7.2 when indexing.

`SQLSTATE[HY000]: General error: 21 library routine called out of sequence
`

It's fixed in the  teamtnt/tntsearch v1.3.1. 

Could you update the teamtnt/tntsearch vendor in the plugin to v1.3.1 ?

Thanks.

**Comment by rhukster** [comment]
will do!

**Comment by rhukster** [comment]
Fixed in next release
