### ISSUE TITLE
Allow searching for phrases

### ISSUE THREAD

**Issue by Flamenco** [trilbymedia/grav-plugin-tntsearch#29]
I added some changes to this plugin.
<img width="567" alt="screen shot 2018-02-27 at 11 29 51 am" src="https://user-images.githubusercontent.com/819940/36747003-c17beb9c-1bc1-11e8-901f-cee42f0d36f1.png">

If this feature is enabled and a query matches all the words, a case sensitive search is made from the getCleanContent results of the matching IDs.  This is very fast on a site with about 1000 pages.

PR is pending conversation.

**Comment by rhukster** [comment]
Is this PR submitted? I would like to test it out.

**Comment by Flamenco** [comment]
This is not submitted yet.  I was waiting to see if there was interest first. I will post a draft tomorrow.
