### ISSUE TITLE
toggle build in CSS // inline JS

### ISSUE THREAD

**Issue by jimblue** [trilbymedia/grav-plugin-tntsearch#3]
Hi!

A nice feature to add would be an option to toggle the build in CSS / JS. (like langSwitcher plugin does for exemple)

Also leave an option to include the JS script inline.

Thanks guys

**Comment by rhukster** [comment]
Actually i planned on putting this in, but just forgot!  I'll make sure it's added for next release.

**Comment by jimblue** [comment]
@rhukster cool thanks man!
