### ISSUE TITLE
Plus prefix should result in boolean search requiring a word

### ISSUE THREAD

**Issue by Flamenco** [trilbymedia/grav-plugin-tntsearch#35]

**Comment by rhukster** [comment]
Need more info...

**Comment by Flamenco** [comment]
AKA google search syntax:
```
+Andy +Rocks
```
This would require 'Andy' and 'Rocks' in the document.  The current implementation will return documents with either/or.

**Comment by rhukster** [comment]
It seems it's a current limitation of the library, that you can't put a + or - on the first item.

`Andy+Rocks` does seem to work for me though.
