### ISSUE TITLE
Weird behaviour both on indexing and searching

### ISSUE THREAD

**Issue by Soulhub** [trilbymedia/grav-plugin-tntsearch#38]
On indexing:
From CLI, seems to be working fine. Outputs the exact number of indexed pages I am expecting to see and completes with no errors.
From the admin plugin, initial indexing keeps on going for hours and nothing happens. Adding to that, when I create the index from CLI and then go to the admin plugin, it stil shows 0 indexed documents (but not the notice that I have to create the index).

On searching:
Even if the CLI indexing completes with no errors, I get just a couple of results no matter what I search for. Sometimes not even one, when I know that the search term exists. Same thing with CLI query or on site. I also cannot search in a language different than English.

Latest version of Grav and TNTSearch plugin.

**Comment by rhukster** [comment]
What do you have for a filter? maybe provide your configuration YAML file?

**Comment by rhukster** [comment]
Multilanguage support has just been added to the `feature/multilang` branch.  After some testing it will be merged into the develop branch but probably have a Grav 1.6 requirement.

Regarding your index issue, i'm wondering if its' related to a plugin you might have installed.  The indexing is done in admin context, and if you have some plugin that is required, or needs to run in 'site' context, it might cause an issue.  There was another ticket regarding some different behavior in admin vs site and the CLI runs in site context.  

I need to think about how this can be better addressed.

**Comment by rhukster** [comment]
Multilang is in the 3.0 beta.... should be released as stable alongside Grav 1.6
