### ISSUE TITLE
Plugin icon choice

### ISSUE THREAD

**Issue by paulhibbitts** [trilbymedia/grav-plugin-tntsearch#4]
I've been really impressed with this plugin so far, esp. the fuzzy search feature!

I know some might think this a minor issue, but the choice of a bomb as icon seems to be both problematic both in terms of the current world situation and often being used for system error messages (i.e. Mac).

I appreciate the choices in font-awesome are very limited, but going through all the icons these looked like some possible alternatives:

![2017-08-19_09-51-21](https://user-images.githubusercontent.com/1812771/29488693-0f6185d6-84c5-11e7-8df3-5a7d75b58f9e.png)

![2017-08-19_09-51-58](https://user-images.githubusercontent.com/1812771/29488694-11c4167c-84c5-11e7-9fde-38a916d2f319.png)

![2017-08-19_09-51-04](https://user-images.githubusercontent.com/1812771/29488692-0c62fbc6-84c5-11e7-81e8-31f730bbb67f.png)

Any thoughts/comments or other suggestions?

Thanks very much,
Paul

**Comment by rhukster** [comment]
Even a cartoon bomb is too provocative these days? What would Batman say!

![giphy](https://user-images.githubusercontent.com/1084697/29542810-c523d1a0-8699-11e7-99a5-822bc444d531.gif)

**Comment by paulhibbitts** [comment]
That is such a classic clip though 😉

**Comment by rhukster** [comment]
Went with binocs.. closing.

**Comment by paulhibbitts** [comment]
Awesome, thanks so much for making this change!
