### ISSUE TITLE
Unable to index

### ISSUE THREAD

**Issue by Lucannus** [trilbymedia/grav-plugin-tntsearch#40]
After doing latest updates to Grav, TNT Search and my OS (Devuan [debian fork]) I am now no longer to Index. Search always returns a "Found 0 results" no matter what is being searched for.

Was working before updates.

**Comment by kiselli** [comment]
+1

**Comment by ArsMediaBrasil** [comment]
Hi @kiselli  and @Lucannus 
I'm having the same issue and it's all set under user/config/plugins/tntsearch.yml
Since the last php upgrade I just can't index any of the pages on a blog with **mediator** theme.
Are there other options to use on this theme instead of TNT?
Many thanks

**Comment by Lucannus** [comment]
@kiselli here is my current yaml.

enabled: true
search_route: /search
query_route: /s
built_in_css: true
built_in_js: true
built_in_search_page: true
search_type: auto
fuzzy: true
stemmer: default
display_route: true
display_hits: true
display_time: true
live_uri_update: true
limit: '20'
min: '3'
snippet: '300'
index_page_by_default: true
powered_by: true

**Comment by Lucannus** [comment]
odd thing within grav, the plugin shows the search filter as "taxonomy@: { category: [news] }"

**Comment by Lucannus** [comment]
I saved the configuration that grav had and it added to my yaml. 

filter:
    items:
       taxonomy@:
          category:
             - news

**Comment by nipeco** [comment]
Hi @Lucannus did you get TNT back to work? Is there any progress?

**Comment by rvreugde** [comment]
Does not work for me...
Filter changed to taxonomy@: { category: [docs] }, still 0 documents indexed.
Filter removed: still 0 documents indexed.

Also other grav sites experience this problem...

**Comment by nipeco** [comment]
@rvreugde Look in the files of your posts, the type should be mentioned there and include this type in the filter. It says '0 documents indexed' because the filter doesn't match to any posts of your Grav installation.

**Comment by rvreugde** [comment]
@nipeco Where can I exactly see the type. Is it the "Page Template" in de Advanced section.
Or better, how should the filer be to just index all content?

**Comment by rvreugde** [comment]
@nipeco OK, I found a solution, indexing works with: **'@root.descendants'** filter.

**Comment by nipeco** [comment]
@rvreugde How does this fix the issue?

You can find it switching to 'expert' mode on the top right of the page settings. Then I see something like this:

```
title: 'User''s Guide'
taxonomy:
    category:
        - docs
```

The category does it.
