### ISSUE TITLE
TNTSearch won't index

### ISSUE THREAD

**Issue by rvreugde** [trilbymedia/grav-plugin-tntsearch#43]
Hello,

TNT Search indexes no more. I even have removed the plugin and the configuration files, but after re-installing, it does not work.

When I invoke the re-index via the interface, there are 0 pages indexed. Also via command line:
```
[root@...]# bin/plugin tntsearch index

Re-indexing Search

Total rows 0
Done.
```

Can you help?

**Comment by ArsMediaBrasil** [comment]
Hello @rvreugde 

I had the same issue and solved by filtering a tag I've used in all pages:

index_page_by_default: true
filter:
  items:
    '@taxonomy.tag':
      - 'my_tag'

**Comment by rhukster** [comment]
I've set the default filter to search all pages.  But that's just to prove it works, you really should only filter what you need.
