### ISSUE TITLE
When saving a page in GRAV I get the following error:

### ISSUE THREAD

**Issue by tinhut** [trilbymedia/grav-plugin-tntsearch#44]
"Class 'Grav\Plugin\TNTSearch\Yaml' not found"
at 
           if (is_string($filter['items'])) {
                **$filter['items'] = Yaml::parse($filter['items']);**
            }

Re installing the plugin did not help.

**Comment by rhukster** [comment]
https://github.com/trilbymedia/grav-plugin-tntsearch/pull/41

Already fixed.. i need to get a new release out.
