### ISSUE TITLE
Not working depending on site settings for cache

### ISSUE THREAD

**Issue by leotiger** [trilbymedia/grav-plugin-tntsearch#47]
The only way this plugin works for me is to enable file as the cache driver. With volatile caches like Memcached or APCu and cache invalidation method set to never, the plugin provokes execution timeouts in all contexts: admin, frontend...

**Comment by rhukster** [comment]
I'm using APCu, and not having any issues.

**Comment by leotiger** [comment]
True, I've tested on my local machine and it works with APCu. I have to investigate a bit more.

**Comment by leotiger** [comment]
Played around with the webserver settings, not sure what makes the difference but it works now.

**Comment by leotiger** [comment]
I finally found a solution for the bizarre behavior that provoked execution timeouts, don't know why but specifying a high load priority for the js file solved the problem:

```
$this->grav['assets']->addJs('plugin://tntsearch/assets/tntsearch.js', 121);
```

On my local server this is not necessary. Seems that the environment plays a role as the site on my local server uses the same content and configuration.
