### ISSUE TITLE
Could not find driver

### ISSUE THREAD

**Issue by Rikusen0335** [trilbymedia/grav-plugin-tntsearch#49]
Hello, when I press the `Index Content`, that appears a message "could not find driver".
I have 3+ articles, well I want to know how to fix it.

Running on Raspberry Pi3 B+.

**Comment by rhukster** [comment]
You are missing some of the requirements: https://github.com/trilbymedia/grav-plugin-tntsearch#requirements

**Comment by Rikusen0335** [comment]
Thanks, it was fixed!
The command for Linux user:
`sudo apt install sqlite3`
`sudo apt install php7.0-pdo`
`sudo apt install php7.0-sqlite3`
`sudo apt install php7.0-mysql`
but this is for `php7.0`.

**Comment by ginkgomzd** [comment]
I just had to enable the php modules, probably depends on how you install php. I used the tasksel lamp on Ubuntu 18.04.

`` sudo phpenmod pdo pdo_sqlite pdo_mysql``
