### ISSUE TITLE
2.0.4 release not released?

### ISSUE THREAD

**Issue by thomasjsn** [trilbymedia/grav-plugin-tntsearch#55]
I'd like the functionality added in 749e37901f93aadfb6395aad3b2db9407e78e4cb, but it looks like 2.0.4 has not been released yet. I still have 2.0.3 on my instance and 2.0.3 is the latest tag on the release page for this repo.

**Comment by rhukster** [comment]
Doh! I released 2.0.4 but never pushed the tag.  That's done now, and 2.0.4 should start showing up.
