### ISSUE TITLE
Filter before search - limit search query/results

### ISSUE THREAD

**Issue by webmaster1-sneb** [trilbymedia/grav-plugin-tntsearch#59]
Being able to set a filter (collection) at before query, at page level, in order to get only a subset of results (if they are in the collection).

Expl : 
root/
- subA/  --> here. searching yields subpages of subA matching searched keywords 
  tntsearch:
    filter:
        items: '@self.children'
- subB/ --> here. searching yields blog pages tagged birds matching searched keywords   
    tntsearch:
        filter:
            items: '@taxonomy': {tag: birds, category: blog}

**Comment by rhukster** [comment]
This is really beyond the capabilities of the TNTSearch plugin.  The content is indexed based on a single collection, and the query is simply a textual search of that index.  

To filter results further, you would have to get all the results, then for each page returned, look up that page, and inspect it's taxonomy and then filter.  You can actually do this with the results on your own by overridding the `tntquery-ajax.html.twig` template in your theme or plugin.

https://github.com/trilbymedia/grav-plugin-tntsearch/blob/develop/templates/tntquery-ajax.html.twig

**Comment by webmaster1-sneb** [comment]
I Will follow that lead.
Thanks Andy !
