### ISSUE TITLE
Conflict between bootstrap 4.0.0 and tntsearch

### ISSUE THREAD

**Issue by girald0** [trilbymedia/grav-plugin-tntsearch#6]
Hi,

There is a conflict between tntsearch's and bootstrap's javascripts. I don't know exactly what the problem is, as I don't have a lot of knowledge of javascript or jquery, but when tntsearch is called it breaks some of the bootstrap components, as dropdowns or slideshows. It does not matter whenever tntsearch.js is called, before or after bootstrap's js, because then only tntsearch works.

Here you have the link on the grav's discourse topic, where I asked for help before coming here to see if anyone encountered the same issue as me: https://discourse.getgrav.org/t/conflict-between-tntsearch-and-bootstrap/4455

**Comment by rhukster** [comment]
JS has been rewritten.  I think it should work now.
