### ISSUE TITLE
GravConnector dont use custom class defined in search_object_type

### ISSUE THREAD

**Issue by fosil** [trilbymedia/grav-plugin-tntsearch#63]
I use custom class with config option search_object_type but connector dont use it.

GravConnector.php on line 28:

```
$gtnt = new GravTNTSearch();
```

change to:

```
$gtnt = \Grav\Plugin\TNTSearchPlugin::getSearchObjectType();
```

would be a simple solution.

**Comment by rhukster** [comment]
Good catch. fixed in develop
