### ISSUE TITLE
Error "SQLSTATE[HY000]: General error: 8 attempt to write a readonly database" when saving a page

### ISSUE THREAD

**Issue by rafvandevreugde** [trilbymedia/grav-plugin-tntsearch#68]
When I want to save a page I got the following error:

`SQLSTATE[HY000]: General error: 8 attempt to write a readonly database`

When I disable the TNTSearch plugin, the error disappears.
Also, when I want to re-arrange my pages in a subfolder, this error occurs and the page is duplicated.

**Comment by rhukster** [comment]
The permission of the generated `user/data/tntsearch/grav.index` database file is not writable.  You need to ensure this is writable by the webserver. https://learn.getgrav.org/16/troubleshooting/permissions
