### ISSUE TITLE
Multilang support isn't full

### ISSUE THREAD

**Issue by Sogl** [trilbymedia/grav-plugin-tntsearch#72]
Hello!

Try to use this plugin on my site (language is Russian in my case). Some parts of it use hardcoded lang values:
1. Powered by:
https://github.com/trilbymedia/grav-plugin-tntsearch/blob/e7dd087047a73a8264860213c06f32f28d7d02be/templates/partials/tntsearch.html.twig#L26
2. Page title:
https://github.com/trilbymedia/grav-plugin-tntsearch/blob/develop/pages/search.md

Maybe I missed some parts, but it's good to complete multilang support 😉

**Comment by Sogl** [comment]
PR for fix 1st at least: https://github.com/trilbymedia/grav-plugin-tntsearch/pull/74

For 2nd, need to create `/search/search.md` file with `title: What_text_you_want`

**Comment by rhukster** [comment]
Another simple fix is to just copy the twig file to your theme (using the same path) and make the edits.

**Comment by rhukster** [comment]
merged also
