### ISSUE TITLE
Marathi (Indian Language) search issue

### ISSUE THREAD

**Issue by sawadhkarkushal** [trilbymedia/grav-plugin-tntsearch#77]
We have issue while searching Marathi word using grav tntsearch.  If we search complete  word in marathi, it give proper result, but if word is combine, the result is not proper. Please help us to solve this issue.

**Comment by rhukster** [comment]
I feel this is related to character encoding.  unfortunately, the issue lies in the TNTSearch library we are using.  You would have to post an issue on their issue tracker: https://github.com/teamtnt/tntsearch/issues
