### ISSUE TITLE
TNTSearch / Grav v1.7.0-rc.2 + Admin v1.10.0-rc.2 incompatibility ?

### ISSUE THREAD

**Issue by AntoineMmh** [trilbymedia/grav-plugin-tntsearch#78]
Hi.

Since I've installed Grav v1.7.0-rc.2 and Admin v1.10.0-rc.2 I'm unable to reindex with TNTSearch from Admin Panel.
Reindexing in commande line with "bin/plugin tntsearch index" works well. But in Admin Panel I always have "Processed 1 languages, each with 0 documents reindexed" or "0 documents reindexed" (if I remove my french translation).

Any other user with this issue ?

**Comment by AntoineMmh** [comment]
Nobody else get this issue?

**Comment by rhukster** [comment]
It's quite possible, i've not looked into this yet.. you know.. holidays :)

**Comment by AntoineMmh** [comment]
Fixed with TNT Search  v3.1.0 update
