### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by beamaria** [trilbymedia/grav-plugin-tntsearch#88]
I've installed and activated the plugin. At first it worked out of the box ( I left all the default configurations) but now I have this message:
"Validation failed: search_object_type is not defined in blueprints"
What does this mean?
Working with latest version of GRAV Gantry 5 (Helium skeleton site), on php 7.1

**Comment by rhukster** [comment]
confirmed, fixing...

**Comment by rhukster** [comment]
fixed for next release
