### ISSUE TITLE
Can't perform first index

### ISSUE THREAD

**Issue by JamesApple** [trilbymedia/grav-plugin-tntsearch#9]
Hey guys,

I've been developing a site for a while now on my own computer in MAMP.  I have TNTsearch installed there and it works great.

Now that I've installed a fresh version of **grav** with TNTsearch on my **VPS** I can't get the plugin to perform its first index.

I've tested that **SQLite3** is installed correctly and **PDO** appears to be enabled by default and I've verified that from a php.info page. I'm also running **php7**

When I press the red index content button it just spins _eternally_.

Permissions are set to 775 and everything in the root is owned by apache.  Every other plugin is working as expected and the site is serving properly.

There is no grav.index created in users/data/tnt.search either.

I'm not really certain where I can start looking for problems as I can't find any info about logs or debugging.  Not to mention I don't know very much about php in the first place.

I'd really appreciate any help or advice, I've been trying to get it to work for days now.

**Comment by rhukster** [comment]
Can you test with the CLI index command from the terminal on the VPS?

```
$ bin/plugin tntsearch index
```

**Comment by JamesApple** [comment]
Thanks for responding so quicly
 It returned:
```
Re-indexing Search


                                                     
  [PDOException]                                     
  SQLSTATE[HY000] [14] unable to open database file  
                                                     

index
```

**Comment by rhukster** [comment]
Hmm.. i've not seen that one before, but seems its'a 'thing' with tntsearch.  see https://github.com/teamtnt/tntsearch#creating-an-index

I would guess perhaps you changed some of the default values and didn't use the correct quotes?
