### ISSUE TITLE
[Multilanguage] Index works only for current language

### ISSUE THREAD

**Issue by Gladiak** [trilbymedia/grav-plugin-tntsearch#94]
Hi folks, we have a strange issue with your plugin.
We have 2 languages configured in our Grav site, when we create TNTSearch index only the one related to the current language (the language selected in Grav pages section) works properly.
When we change the language inside the site we have results only for the one correctly indexed.

If we run the cli command (_**bin/plugin tntsearch index**_) we see results only for the slugs in the default language for both languages.

```
Re-indexing

Language: it
Added   1 /it/
Added   2 /it/primi-passi/prova-gratuita
Skipped 3 /panel - redirect only...
Skipped 4 /panel/come-iniziare - redirect only...
Added   5 /it/panel/come-iniziare/introduzione
......
Total rows 95

Language: en
Added   1 /en/
Added   2 /en/primi-passi/prova-gratuita
Skipped 3 /panel - redirect only...
Skipped 4 /panel/come-iniziare - redirect only...
Added   5 /en/panel/come-iniziare/introduzione
....
Total rows 95
```

instead of

```
Re-indexing

Language: it
Added   1 /it/
Added   2 /it/primi-passi/prova-gratuita
Skipped 3 /panel - redirect only...
Skipped 4 /panel/come-iniziare - redirect only...
Added   5 /it/panel/come-iniziare/introduzione
......
Total rows 95

Language: en
Added   1 /en/
Added   2 /en/first-steps/free-trial
Skipped 3 /panel - redirect only...
Skipped 4 /panel/how-to-start - redirect only...
Added   5 /en/panel/how-to-start/introduction
....
Total rows 95
```

Can we index one language at a time, with an optional language parameter ?
How we could fix this ?

Thanks a lot,
Filippo

**Comment by mahagr** [comment]
Yes, this indexing issue has actually been fixed in Grav 1.7. That said, I have added a parameter to the plugin to select the language to be indexed, which should work also in Grav 1.6. Check the parameters with help. :)

**Comment by Gladiak** [comment]
How can I index a specific language using the command-line tool?

I tried the following syntax:

```
bin/plugin tntsearch index en

  Too many arguments, expected arguments "command".

index [--alt]
```

**Comment by gamahachaa** [comment]
Hi, try
`tntsearch index -l en`
works for me

**Comment by rhukster** [comment]
Should be working now, if you have no language it indexes all
